version: 2

project_name: skemr-cli


builds:
  - id: skemr-cli
    main: ./skemr-cli/main.go
    binary: skemr-cli
    env:
      - CGO_ENABLED=1
    goos: [linux]
    goarch: [amd64]

archives:
  - id: skemr-cli
    ids: [skemr-cli]
    files:
        - LICENSE
        - README.md
    formats: [ tar.gz, binary ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]
changelog:
    sort: asc
    filters:
        exclude:
        - "^docs:"
        - "^test:"

checksum:
  name_template: "checksums.txt"