dir: ./skemr-api/test/mocks
pkgname: mocks

packages:
  github.com/walmaa/skemr-api/db/sqlc:
    interfaces:
      Querier:
        config:
          filename: querier_mock.go
  github.com/walmaa/skemr-api/internal/scope:
    interfaces:
      Resolver:
        config:
          filename: scope_resolver_mock.go
  github.com/walmaa/skemr-api/internal/domain/rules:
    interfaces:
      RuleStore:
        config:
          filename: rule_store_mock.go

