services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      APP_ENV: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SMTP_HOST: smtp4dev
      SMTP_PORT: 25
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: ""
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_USER=postgres"
  test-postgres:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_DB=test_db"
      - "POSTGRES_PASSWORD=test_pass"
      - "POSTGRES_USER=test_user"
    volumes:
      - ./skemr-api/testdata/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_ALIAS=local-redis
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: skemr-smtp4dev
    ports:
      - "5000:80"
      - "5025:25"
    environment:
      - ServerOptions__HostName=smtp4dev

networks:
  ci:
    name: gitlab-ci-network