concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "9b30094c7c9e"
  url = "http://gitlab"
  id = 106
  token = "glrt-0YdGVbQJFr7lsDM0Tp9Ylm86MQp0OjEKdToxCw.01.120g9t337"
  token_obtained_at = 2026-02-25T09:36:15Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
