// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: databases.sql

package skemr

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (name, username, password)
VALUES ($1, $2, $3) RETURNING id, name, username, password, project_id
`

type CreateDatabaseParams struct {
	Name     string      `json:"name"`
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase, arg.Name, arg.Username, arg.Password)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.ProjectID,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE
FROM databases
WHERE id = $1
`

func (q *Queries) DeleteDatabase(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, name, username, password, project_id
FROM databases
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDatabase(ctx context.Context, id pgtype.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.ProjectID,
	)
	return i, err
}

const updateDatabase = `-- name: UpdateDatabase :exec
UPDATE databases
SET name = $2,
    username = $3,
    password = $4
WHERE id = $1
    RETURNING id, name, username, password, project_id
`

type UpdateDatabaseParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) UpdateDatabase(ctx context.Context, arg UpdateDatabaseParams) error {
	_, err := q.db.Exec(ctx, updateDatabase,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Password,
	)
	return err
}
