// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package skemr

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RuleScope string

const (
	RuleScopeDatabase RuleScope = "database"
	RuleScopeSchema   RuleScope = "schema"
	RuleScopeTable    RuleScope = "table"
	RuleScopeColumn   RuleScope = "column"
)

func (e *RuleScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleScope(s)
	case string:
		*e = RuleScope(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleScope: %T", src)
	}
	return nil
}

type NullRuleScope struct {
	RuleScope RuleScope `json:"rule_scope"`
	Valid     bool      `json:"valid"` // Valid is true if RuleScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleScope) Scan(value interface{}) error {
	if value == nil {
		ns.RuleScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleScope), nil
}

type RuleType string

const (
	RuleTypeLock RuleType = "lock"
	RuleTypeWarn RuleType = "warn"
)

func (e *RuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleType(s)
	case string:
		*e = RuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleType: %T", src)
	}
	return nil
}

type NullRuleType struct {
	RuleType RuleType `json:"rule_type"`
	Valid    bool     `json:"valid"` // Valid is true if RuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.RuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleType), nil
}

type Database struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
}

type Project struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Rule struct {
	ID     int64     `json:"id"`
	Name   string    `json:"name"`
	Type   RuleType  `json:"type"`
	Scope  RuleScope `json:"scope"`
	Target string    `json:"target"`
}

type Schema struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Table struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
