// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package skemr

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name)
VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
set name = $2
WHERE id = $1
    RETURNING id, name
`

type UpdateProjectParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject, arg.ID, arg.Name)
	return err
}
