/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as projectProjectsProjectIdRouteRouteImport } from './routes/(project)/projects/$projectId/route'
import { Route as projectProjectsProjectIdIndexRouteImport } from './routes/(project)/projects/$projectId/index'
import { Route as projectProjectsProjectIdSettingsIndexRouteImport } from './routes/(project)/projects/$projectId/settings/index'
import { Route as projectProjectsProjectIdCiCdIndexRouteImport } from './routes/(project)/projects/$projectId/ci-cd/index'
import { Route as projectProjectsProjectIdAccessTokensIndexRouteImport } from './routes/(project)/projects/$projectId/access-tokens/index'
import { Route as projectProjectsProjectIdDatabasesDatabaseIdIndexRouteImport } from './routes/(project)/projects/$projectId/databases/$databaseId/index'
import { Route as projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRouteImport } from './routes/(project)/projects/$projectId/databases/$databaseId/rules/index'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const projectProjectsProjectIdRouteRoute =
  projectProjectsProjectIdRouteRouteImport.update({
    id: '/(project)/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const projectProjectsProjectIdIndexRoute =
  projectProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)
const projectProjectsProjectIdSettingsIndexRoute =
  projectProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)
const projectProjectsProjectIdCiCdIndexRoute =
  projectProjectsProjectIdCiCdIndexRouteImport.update({
    id: '/ci-cd/',
    path: '/ci-cd/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)
const projectProjectsProjectIdAccessTokensIndexRoute =
  projectProjectsProjectIdAccessTokensIndexRouteImport.update({
    id: '/access-tokens/',
    path: '/access-tokens/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)
const projectProjectsProjectIdDatabasesDatabaseIdIndexRoute =
  projectProjectsProjectIdDatabasesDatabaseIdIndexRouteImport.update({
    id: '/databases/$databaseId/',
    path: '/databases/$databaseId/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)
const projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute =
  projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRouteImport.update({
    id: '/databases/$databaseId/rules/',
    path: '/databases/$databaseId/rules/',
    getParentRoute: () => projectProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/projects/$projectId': typeof projectProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/': typeof projectProjectsProjectIdIndexRoute
  '/projects/$projectId/access-tokens/': typeof projectProjectsProjectIdAccessTokensIndexRoute
  '/projects/$projectId/ci-cd/': typeof projectProjectsProjectIdCiCdIndexRoute
  '/projects/$projectId/settings/': typeof projectProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/databases/$databaseId/': typeof projectProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/projects/$projectId/databases/$databaseId/rules/': typeof projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/projects/$projectId': typeof projectProjectsProjectIdIndexRoute
  '/projects/$projectId/access-tokens': typeof projectProjectsProjectIdAccessTokensIndexRoute
  '/projects/$projectId/ci-cd': typeof projectProjectsProjectIdCiCdIndexRoute
  '/projects/$projectId/settings': typeof projectProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/databases/$databaseId': typeof projectProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/projects/$projectId/databases/$databaseId/rules': typeof projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(project)/projects/$projectId': typeof projectProjectsProjectIdRouteRouteWithChildren
  '/(project)/projects/$projectId/': typeof projectProjectsProjectIdIndexRoute
  '/(project)/projects/$projectId/access-tokens/': typeof projectProjectsProjectIdAccessTokensIndexRoute
  '/(project)/projects/$projectId/ci-cd/': typeof projectProjectsProjectIdCiCdIndexRoute
  '/(project)/projects/$projectId/settings/': typeof projectProjectsProjectIdSettingsIndexRoute
  '/(project)/projects/$projectId/databases/$databaseId/': typeof projectProjectsProjectIdDatabasesDatabaseIdIndexRoute
  '/(project)/projects/$projectId/databases/$databaseId/rules/': typeof projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/'
    | '/projects/$projectId/access-tokens/'
    | '/projects/$projectId/ci-cd/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/databases/$databaseId/'
    | '/projects/$projectId/databases/$databaseId/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId/access-tokens'
    | '/projects/$projectId/ci-cd'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/databases/$databaseId'
    | '/projects/$projectId/databases/$databaseId/rules'
  id:
    | '__root__'
    | '/(home)'
    | '/(home)/'
    | '/(project)/projects/$projectId'
    | '/(project)/projects/$projectId/'
    | '/(project)/projects/$projectId/access-tokens/'
    | '/(project)/projects/$projectId/ci-cd/'
    | '/(project)/projects/$projectId/settings/'
    | '/(project)/projects/$projectId/databases/$databaseId/'
    | '/(project)/projects/$projectId/databases/$databaseId/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  projectProjectsProjectIdRouteRoute: typeof projectProjectsProjectIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(project)/projects/$projectId': {
      id: '/(project)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof projectProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(project)/projects/$projectId/': {
      id: '/(project)/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof projectProjectsProjectIdIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
    '/(project)/projects/$projectId/settings/': {
      id: '/(project)/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof projectProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
    '/(project)/projects/$projectId/ci-cd/': {
      id: '/(project)/projects/$projectId/ci-cd/'
      path: '/ci-cd'
      fullPath: '/projects/$projectId/ci-cd/'
      preLoaderRoute: typeof projectProjectsProjectIdCiCdIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
    '/(project)/projects/$projectId/access-tokens/': {
      id: '/(project)/projects/$projectId/access-tokens/'
      path: '/access-tokens'
      fullPath: '/projects/$projectId/access-tokens/'
      preLoaderRoute: typeof projectProjectsProjectIdAccessTokensIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
    '/(project)/projects/$projectId/databases/$databaseId/': {
      id: '/(project)/projects/$projectId/databases/$databaseId/'
      path: '/databases/$databaseId'
      fullPath: '/projects/$projectId/databases/$databaseId/'
      preLoaderRoute: typeof projectProjectsProjectIdDatabasesDatabaseIdIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
    '/(project)/projects/$projectId/databases/$databaseId/rules/': {
      id: '/(project)/projects/$projectId/databases/$databaseId/rules/'
      path: '/databases/$databaseId/rules'
      fullPath: '/projects/$projectId/databases/$databaseId/rules/'
      preLoaderRoute: typeof projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRouteImport
      parentRoute: typeof projectProjectsProjectIdRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface projectProjectsProjectIdRouteRouteChildren {
  projectProjectsProjectIdIndexRoute: typeof projectProjectsProjectIdIndexRoute
  projectProjectsProjectIdAccessTokensIndexRoute: typeof projectProjectsProjectIdAccessTokensIndexRoute
  projectProjectsProjectIdCiCdIndexRoute: typeof projectProjectsProjectIdCiCdIndexRoute
  projectProjectsProjectIdSettingsIndexRoute: typeof projectProjectsProjectIdSettingsIndexRoute
  projectProjectsProjectIdDatabasesDatabaseIdIndexRoute: typeof projectProjectsProjectIdDatabasesDatabaseIdIndexRoute
  projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute: typeof projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute
}

const projectProjectsProjectIdRouteRouteChildren: projectProjectsProjectIdRouteRouteChildren =
  {
    projectProjectsProjectIdIndexRoute: projectProjectsProjectIdIndexRoute,
    projectProjectsProjectIdAccessTokensIndexRoute:
      projectProjectsProjectIdAccessTokensIndexRoute,
    projectProjectsProjectIdCiCdIndexRoute:
      projectProjectsProjectIdCiCdIndexRoute,
    projectProjectsProjectIdSettingsIndexRoute:
      projectProjectsProjectIdSettingsIndexRoute,
    projectProjectsProjectIdDatabasesDatabaseIdIndexRoute:
      projectProjectsProjectIdDatabasesDatabaseIdIndexRoute,
    projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute:
      projectProjectsProjectIdDatabasesDatabaseIdRulesIndexRoute,
  }

const projectProjectsProjectIdRouteRouteWithChildren =
  projectProjectsProjectIdRouteRoute._addFileChildren(
    projectProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  projectProjectsProjectIdRouteRoute:
    projectProjectsProjectIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
