// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: database_entities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseEntity = `-- name: CreateDatabaseEntity :one
INSERT INTO database_entities
(project_id, database_id, entity_type, parent_id, name, attributes, fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
`

type CreateDatabaseEntityParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	DatabaseID  uuid.UUID          `json:"database_id"`
	EntityType  DatabaseEntityType `json:"entity_type"`
	ParentID    *uuid.UUID         `json:"parent_id"`
	Name        string             `json:"name"`
	Attributes  []byte             `json:"attributes"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
}

func (q *Queries) CreateDatabaseEntity(ctx context.Context, arg CreateDatabaseEntityParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, createDatabaseEntity,
		arg.ProjectID,
		arg.DatabaseID,
		arg.EntityType,
		arg.ParentID,
		arg.Name,
		arg.Attributes,
		arg.Fingerprint,
	)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntities = `-- name: GetDatabaseEntities :many
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE database_id = $1
  AND (entity_type = $2 OR $2 IS NULL)
  AND (parent_id = $3 OR $3 IS NULL)
`

type GetDatabaseEntitiesParams struct {
	DatabaseID uuid.UUID              `json:"database_id"`
	EntityType NullDatabaseEntityType `json:"entity_type"`
	ParentID   *uuid.UUID             `json:"parent_id"`
}

func (q *Queries) GetDatabaseEntities(ctx context.Context, arg GetDatabaseEntitiesParams) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntities, arg.DatabaseID, arg.EntityType, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.ProjectID,
			&i.DatabaseID,
			&i.Status,
			&i.DeletedAt,
			&i.FirstSeenAt,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntitiesByDatabaseId = `-- name: GetDatabaseEntitiesByDatabaseId :many
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE database_id = $1
`

func (q *Queries) GetDatabaseEntitiesByDatabaseId(ctx context.Context, databaseID uuid.UUID) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByDatabaseId, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.ProjectID,
			&i.DatabaseID,
			&i.Status,
			&i.DeletedAt,
			&i.FirstSeenAt,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntitiesByDatabaseIdAndParentId = `-- name: GetDatabaseEntitiesByDatabaseIdAndParentId :many
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE database_id = $1
  AND parent_id = $2
`

type GetDatabaseEntitiesByDatabaseIdAndParentIdParams struct {
	DatabaseID uuid.UUID  `json:"database_id"`
	ParentID   *uuid.UUID `json:"parent_id"`
}

func (q *Queries) GetDatabaseEntitiesByDatabaseIdAndParentId(ctx context.Context, arg GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByDatabaseIdAndParentId, arg.DatabaseID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.ProjectID,
			&i.DatabaseID,
			&i.Status,
			&i.DeletedAt,
			&i.FirstSeenAt,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntitiesByProjectId = `-- name: GetDatabaseEntitiesByProjectId :many
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE project_id = $1
`

func (q *Queries) GetDatabaseEntitiesByProjectId(ctx context.Context, projectID uuid.UUID) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.ProjectID,
			&i.DatabaseID,
			&i.Status,
			&i.DeletedAt,
			&i.FirstSeenAt,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntity = `-- name: GetDatabaseEntity :one
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDatabaseEntity(ctx context.Context, id uuid.UUID) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntity, id)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntityByDatabaseIdAndTypeAndParentAndName = `-- name: GetDatabaseEntityByDatabaseIdAndTypeAndParentAndName :one
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE database_id = $1
  AND entity_type = $2
  AND parent_id IS NOT DISTINCT FROM $3 -- this can be null in case of schema so we use is not distinct to compare
  AND name = $4
LIMIT 1
`

type GetDatabaseEntityByDatabaseIdAndTypeAndParentAndNameParams struct {
	DatabaseID uuid.UUID          `json:"database_id"`
	EntityType DatabaseEntityType `json:"entity_type"`
	ParentID   *uuid.UUID         `json:"parent_id"`
	Name       string             `json:"name"`
}

func (q *Queries) GetDatabaseEntityByDatabaseIdAndTypeAndParentAndName(ctx context.Context, arg GetDatabaseEntityByDatabaseIdAndTypeAndParentAndNameParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntityByDatabaseIdAndTypeAndParentAndName,
		arg.DatabaseID,
		arg.EntityType,
		arg.ParentID,
		arg.Name,
	)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntityByFingerprint = `-- name: GetDatabaseEntityByFingerprint :one
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE database_id = $1
  AND fingerprint = $2
LIMIT 1
`

type GetDatabaseEntityByFingerprintParams struct {
	DatabaseID  uuid.UUID   `json:"database_id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) GetDatabaseEntityByFingerprint(ctx context.Context, arg GetDatabaseEntityByFingerprintParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntityByFingerprint, arg.DatabaseID, arg.Fingerprint)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntityByProjectIdAndId = `-- name: GetDatabaseEntityByProjectIdAndId :one
SELECT id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
FROM database_entities
WHERE id = $1
  AND project_id = $2
LIMIT 1
`

type GetDatabaseEntityByProjectIdAndIdParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetDatabaseEntityByProjectIdAndId(ctx context.Context, arg GetDatabaseEntityByProjectIdAndIdParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntityByProjectIdAndId, arg.ID, arg.ProjectID)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const updateDatabaseEntity = `-- name: UpdateDatabaseEntity :one
UPDATE database_entities
SET name = COALESCE($1, name),
    attributes = COALESCE($2, attributes),
    fingerprint = COALESCE($3, fingerprint),
    parent_id = COALESCE($4, parent_id)
WHERE id = $5
RETURNING id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
`

type UpdateDatabaseEntityParams struct {
	Name        pgtype.Text `json:"name"`
	Attributes  []byte      `json:"attributes"`
	Fingerprint pgtype.Text `json:"fingerprint"`
	ParentID    *uuid.UUID  `json:"parent_id"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDatabaseEntity(ctx context.Context, arg UpdateDatabaseEntityParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, updateDatabaseEntity,
		arg.Name,
		arg.Attributes,
		arg.Fingerprint,
		arg.ParentID,
		arg.ID,
	)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const updateDatabaseEntityAsDeleted = `-- name: UpdateDatabaseEntityAsDeleted :exec
UPDATE database_entities
SET status     = 'deleted',
    deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDatabaseEntityAsDeleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateDatabaseEntityAsDeleted, id)
	return err
}

const updateDatabaseEntityName = `-- name: UpdateDatabaseEntityName :one
UPDATE database_entities
SET name = $1
WHERE id = $2
RETURNING id, fingerprint, project_id, database_id, status, deleted_at, first_seen_at, entity_type, parent_id, name, attributes, created_at
`

type UpdateDatabaseEntityNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDatabaseEntityName(ctx context.Context, arg UpdateDatabaseEntityNameParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, updateDatabaseEntityName, arg.Name, arg.ID)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.ProjectID,
		&i.DatabaseID,
		&i.Status,
		&i.DeletedAt,
		&i.FirstSeenAt,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}
