// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: database_changes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseChange = `-- name: CreateDatabaseChange :one
INSERT INTO database_changes
    (database_id, entity_id, action)
VALUES ($1, $2, $3)
RETURNING id, database_id, entity_id, action, created_at
`

type CreateDatabaseChangeParams struct {
	DatabaseID uuid.UUID                `json:"database_id"`
	EntityID   uuid.UUID                `json:"entity_id"`
	Action     MigrationStatementAction `json:"action"`
}

func (q *Queries) CreateDatabaseChange(ctx context.Context, arg CreateDatabaseChangeParams) (DatabaseChange, error) {
	row := q.db.QueryRow(ctx, createDatabaseChange, arg.DatabaseID, arg.EntityID, arg.Action)
	var i DatabaseChange
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.EntityID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseChangeByDatabaseIdAndId = `-- name: GetDatabaseChangeByDatabaseIdAndId :one
SELECT id, database_id, entity_id, action, created_at
FROM database_changes c
WHERE c.id = $1
  AND c.database_id = $2
LIMIT 1
`

type GetDatabaseChangeByDatabaseIdAndIdParams struct {
	ID         uuid.UUID `json:"id"`
	DatabaseID uuid.UUID `json:"database_id"`
}

func (q *Queries) GetDatabaseChangeByDatabaseIdAndId(ctx context.Context, arg GetDatabaseChangeByDatabaseIdAndIdParams) (DatabaseChange, error) {
	row := q.db.QueryRow(ctx, getDatabaseChangeByDatabaseIdAndId, arg.ID, arg.DatabaseID)
	var i DatabaseChange
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.EntityID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseChangesByDatabaseIdAndId = `-- name: GetDatabaseChangesByDatabaseIdAndId :many
SELECT id, database_id, entity_id, action, created_at
FROM database_changes c
WHERE c.database_id = $1
ORDER BY c.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type GetDatabaseChangesByDatabaseIdAndIdParams struct {
	DatabaseID uuid.UUID   `json:"database_id"`
	Offset     pgtype.Int4 `json:"offset"`
	Limit      pgtype.Int4 `json:"limit"`
}

func (q *Queries) GetDatabaseChangesByDatabaseIdAndId(ctx context.Context, arg GetDatabaseChangesByDatabaseIdAndIdParams) ([]DatabaseChange, error) {
	rows, err := q.db.Query(ctx, getDatabaseChangesByDatabaseIdAndId, arg.DatabaseID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseChange{}
	for rows.Next() {
		var i DatabaseChange
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.EntityID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
