// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: database_entities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseEntity = `-- name: CreateDatabaseEntity :one
INSERT INTO database_entities
(project_id, database_id, entity_type, parent_id, name)
VALUES
($1, $2, $3, $4, $5)
RETURNING id, project_id, database_id, entity_type, parent_id, name, created_at
`

type CreateDatabaseEntityParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	DatabaseID uuid.UUID          `json:"database_id"`
	EntityType DatabaseEntityType `json:"entity_type"`
	ParentID   *uuid.UUID         `json:"parent_id"`
	Name       string             `json:"name"`
}

func (q *Queries) CreateDatabaseEntity(ctx context.Context, arg CreateDatabaseEntityParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, createDatabaseEntity,
		arg.ProjectID,
		arg.DatabaseID,
		arg.EntityType,
		arg.ParentID,
		arg.Name,
	)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DatabaseID,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntitiesByDatabaseId = `-- name: GetDatabaseEntitiesByDatabaseId :many
SELECT  id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE database_id = $1
    AND ( entity_type = $2 OR $2 IS NULL)
    AND ( parent_id = $3 OR $3 IS NULL)
`

type GetDatabaseEntitiesByDatabaseIdParams struct {
	DatabaseID uuid.UUID              `json:"database_id"`
	EntityType NullDatabaseEntityType `json:"entity_type"`
	ParentID   *uuid.UUID             `json:"parent_id"`
}

func (q *Queries) GetDatabaseEntitiesByDatabaseId(ctx context.Context, arg GetDatabaseEntitiesByDatabaseIdParams) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByDatabaseId, arg.DatabaseID, arg.EntityType, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DatabaseID,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntitiesByDatabaseIdAndParentId = `-- name: GetDatabaseEntitiesByDatabaseIdAndParentId :many
SELECT  id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE database_id = $1 AND parent_id = $2
`

type GetDatabaseEntitiesByDatabaseIdAndParentIdParams struct {
	DatabaseID uuid.UUID  `json:"database_id"`
	ParentID   *uuid.UUID `json:"parent_id"`
}

func (q *Queries) GetDatabaseEntitiesByDatabaseIdAndParentId(ctx context.Context, arg GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByDatabaseIdAndParentId, arg.DatabaseID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DatabaseID,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntitiesByProjectId = `-- name: GetDatabaseEntitiesByProjectId :many
SELECT id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE project_id = $1
`

func (q *Queries) GetDatabaseEntitiesByProjectId(ctx context.Context, projectID uuid.UUID) ([]DatabaseEntity, error) {
	rows, err := q.db.Query(ctx, getDatabaseEntitiesByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseEntity{}
	for rows.Next() {
		var i DatabaseEntity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DatabaseID,
			&i.EntityType,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseEntity = `-- name: GetDatabaseEntity :one
SELECT id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDatabaseEntity(ctx context.Context, id uuid.UUID) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntity, id)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DatabaseID,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntityByDatabaseIdAndTypeAndName = `-- name: GetDatabaseEntityByDatabaseIdAndTypeAndName :one
SELECT id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE database_id = $1 AND entity_type = $2 AND name = $3
LIMIT 1
`

type GetDatabaseEntityByDatabaseIdAndTypeAndNameParams struct {
	DatabaseID uuid.UUID          `json:"database_id"`
	EntityType DatabaseEntityType `json:"entity_type"`
	Name       string             `json:"name"`
}

func (q *Queries) GetDatabaseEntityByDatabaseIdAndTypeAndName(ctx context.Context, arg GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntityByDatabaseIdAndTypeAndName, arg.DatabaseID, arg.EntityType, arg.Name)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DatabaseID,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseEntityByProjectIdAndId = `-- name: GetDatabaseEntityByProjectIdAndId :one
SELECT id, project_id, database_id, entity_type, parent_id, name, created_at
FROM database_entities
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetDatabaseEntityByProjectIdAndIdParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetDatabaseEntityByProjectIdAndId(ctx context.Context, arg GetDatabaseEntityByProjectIdAndIdParams) (DatabaseEntity, error) {
	row := q.db.QueryRow(ctx, getDatabaseEntityByProjectIdAndId, arg.ID, arg.ProjectID)
	var i DatabaseEntity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DatabaseID,
		&i.EntityType,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
