// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: databases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases
(project_id, display_name, db_name, username, password, host, port, database_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
`

type CreateDatabaseParams struct {
	ProjectID    uuid.UUID        `json:"project_id"`
	DisplayName  string           `json:"display_name"`
	DbName       pgtype.Text      `json:"db_name"`
	Username     pgtype.Text      `json:"username"`
	Password     pgtype.Text      `json:"password"`
	Host         pgtype.Text      `json:"host"`
	Port         pgtype.Int4      `json:"port"`
	DatabaseType NullDatabaseType `json:"database_type"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ProjectID,
		arg.DisplayName,
		arg.DbName,
		arg.Username,
		arg.Password,
		arg.Host,
		arg.Port,
		arg.DatabaseType,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE
FROM databases
WHERE id = $1
`

func (q *Queries) DeleteDatabase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
FROM databases
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDatabase(ctx context.Context, id uuid.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseByIDAndProjectID = `-- name: GetDatabaseByIDAndProjectID :one
SELECT id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
FROM databases
WHERE id = $1
  AND project_id = $2
LIMIT 1
`

type GetDatabaseByIDAndProjectIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetDatabaseByIDAndProjectID(ctx context.Context, arg GetDatabaseByIDAndProjectIDParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseByIDAndProjectID, arg.ID, arg.ProjectID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseByIdAndProject = `-- name: GetDatabaseByIdAndProject :one
SELECT id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
FROM databases
WHERE id = $1
  AND project_id = $2
LIMIT 1
`

type GetDatabaseByIdAndProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetDatabaseByIdAndProject(ctx context.Context, arg GetDatabaseByIdAndProjectParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseByIdAndProject, arg.ID, arg.ProjectID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseByNameAndProject = `-- name: GetDatabaseByNameAndProject :one
SELECT id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
FROM databases
WHERE display_name = $1
  AND project_id = $2
LIMIT 1
`

type GetDatabaseByNameAndProjectParams struct {
	DisplayName string    `json:"display_name"`
	ProjectID   uuid.UUID `json:"project_id"`
}

func (q *Queries) GetDatabaseByNameAndProject(ctx context.Context, arg GetDatabaseByNameAndProjectParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseByNameAndProject, arg.DisplayName, arg.ProjectID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatabasesByProject = `-- name: ListDatabasesByProject :many
SELECT id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
FROM databases
WHERE project_id = $1
`

func (q *Queries) ListDatabasesByProject(ctx context.Context, projectID uuid.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.DbName,
			&i.Username,
			&i.Password,
			&i.Host,
			&i.Port,
			&i.DatabaseType,
			&i.ProjectID,
			&i.LastSyncedAt,
			&i.LastSyncError,
			&i.FailedConnectionAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabase = `-- name: UpdateDatabase :one
UPDATE databases
SET display_name  = COALESCE($1, display_name),
    db_name       = COALESCE($2, db_name),
    username      = COALESCE($3, username),
    password      = COALESCE($4, password),
    host          = COALESCE($5, host),
    port          = COALESCE($6, port),
    database_type = COALESCE($7, database_type)
WHERE id = $8
RETURNING id, display_name, db_name, username, password, host, port, database_type, project_id, last_synced_at, last_sync_error, failed_connection_attempts, created_at, updated_at
`

type UpdateDatabaseParams struct {
	DisplayName  pgtype.Text      `json:"display_name"`
	DbName       pgtype.Text      `json:"db_name"`
	Username     pgtype.Text      `json:"username"`
	Password     pgtype.Text      `json:"password"`
	Host         pgtype.Text      `json:"host"`
	Port         pgtype.Int4      `json:"port"`
	DatabaseType NullDatabaseType `json:"database_type"`
	DatabaseID   uuid.UUID        `json:"database_id"`
}

func (q *Queries) UpdateDatabase(ctx context.Context, arg UpdateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabase,
		arg.DisplayName,
		arg.DbName,
		arg.Username,
		arg.Password,
		arg.Host,
		arg.Port,
		arg.DatabaseType,
		arg.DatabaseID,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DbName,
		&i.Username,
		&i.Password,
		&i.Host,
		&i.Port,
		&i.DatabaseType,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.LastSyncError,
		&i.FailedConnectionAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
