// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DatabaseEntityStatus string

const (
	DatabaseEntityStatusActive  DatabaseEntityStatus = "active"
	DatabaseEntityStatusDeleted DatabaseEntityStatus = "deleted"
)

func (e *DatabaseEntityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DatabaseEntityStatus(s)
	case string:
		*e = DatabaseEntityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DatabaseEntityStatus: %T", src)
	}
	return nil
}

type NullDatabaseEntityStatus struct {
	DatabaseEntityStatus DatabaseEntityStatus `json:"database_entity_status"`
	Valid                bool                 `json:"valid"` // Valid is true if DatabaseEntityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDatabaseEntityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DatabaseEntityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DatabaseEntityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDatabaseEntityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DatabaseEntityStatus), nil
}

type DatabaseEntityType string

const (
	DatabaseEntityTypeDatabase DatabaseEntityType = "database"
	DatabaseEntityTypeSchema   DatabaseEntityType = "schema"
	DatabaseEntityTypeTable    DatabaseEntityType = "table"
	DatabaseEntityTypeColumn   DatabaseEntityType = "column"
)

func (e *DatabaseEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DatabaseEntityType(s)
	case string:
		*e = DatabaseEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for DatabaseEntityType: %T", src)
	}
	return nil
}

type NullDatabaseEntityType struct {
	DatabaseEntityType DatabaseEntityType `json:"database_entity_type"`
	Valid              bool               `json:"valid"` // Valid is true if DatabaseEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDatabaseEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.DatabaseEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DatabaseEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDatabaseEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DatabaseEntityType), nil
}

type DatabaseType string

const (
	DatabaseTypePostgres DatabaseType = "postgres"
)

func (e *DatabaseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DatabaseType(s)
	case string:
		*e = DatabaseType(s)
	default:
		return fmt.Errorf("unsupported scan type for DatabaseType: %T", src)
	}
	return nil
}

type NullDatabaseType struct {
	DatabaseType DatabaseType `json:"database_type"`
	Valid        bool         `json:"valid"` // Valid is true if DatabaseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDatabaseType) Scan(value interface{}) error {
	if value == nil {
		ns.DatabaseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DatabaseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDatabaseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DatabaseType), nil
}

type MigrationStatementAction string

const (
	MigrationStatementActionCreate MigrationStatementAction = "create"
	MigrationStatementActionAlter  MigrationStatementAction = "alter"
	MigrationStatementActionDrop   MigrationStatementAction = "drop"
	MigrationStatementActionInsert MigrationStatementAction = "insert"
	MigrationStatementActionUpdate MigrationStatementAction = "update"
	MigrationStatementActionDelete MigrationStatementAction = "delete"
)

func (e *MigrationStatementAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationStatementAction(s)
	case string:
		*e = MigrationStatementAction(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationStatementAction: %T", src)
	}
	return nil
}

type NullMigrationStatementAction struct {
	MigrationStatementAction MigrationStatementAction `json:"migration_statement_action"`
	Valid                    bool                     `json:"valid"` // Valid is true if MigrationStatementAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationStatementAction) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationStatementAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationStatementAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationStatementAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationStatementAction), nil
}

type MigrationStatus string

const (
	MigrationStatusPending    MigrationStatus = "pending"
	MigrationStatusInProgress MigrationStatus = "in_progress"
	MigrationStatusCompleted  MigrationStatus = "completed"
	MigrationStatusFailed     MigrationStatus = "failed"
)

func (e *MigrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationStatus(s)
	case string:
		*e = MigrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationStatus: %T", src)
	}
	return nil
}

type NullMigrationStatus struct {
	MigrationStatus MigrationStatus `json:"migration_status"`
	Valid           bool            `json:"valid"` // Valid is true if MigrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationStatus), nil
}

type RuleType string

const (
	RuleTypeLocked     RuleType = "locked"
	RuleTypeWarn       RuleType = "warn"
	RuleTypeAdvisory   RuleType = "advisory"
	RuleTypeDeprecated RuleType = "deprecated"
)

func (e *RuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleType(s)
	case string:
		*e = RuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleType: %T", src)
	}
	return nil
}

type NullRuleType struct {
	RuleType RuleType `json:"rule_type"`
	Valid    bool     `json:"valid"` // Valid is true if RuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.RuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleType), nil
}

type Database struct {
	ID                       uuid.UUID          `json:"id"`
	DisplayName              string             `json:"display_name"`
	DbName                   pgtype.Text        `json:"db_name"`
	Username                 pgtype.Text        `json:"username"`
	Password                 pgtype.Text        `json:"password"`
	Host                     pgtype.Text        `json:"host"`
	Port                     pgtype.Int4        `json:"port"`
	DatabaseType             NullDatabaseType   `json:"database_type"`
	ProjectID                uuid.UUID          `json:"project_id"`
	LastSyncedAt             pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncError            pgtype.Text        `json:"last_sync_error"`
	FailedConnectionAttempts int32              `json:"failed_connection_attempts"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type DatabaseEntity struct {
	ID          uuid.UUID            `json:"id"`
	ProjectID   uuid.UUID            `json:"project_id"`
	DatabaseID  uuid.UUID            `json:"database_id"`
	Status      DatabaseEntityStatus `json:"status"`
	DeletedAt   pgtype.Timestamptz   `json:"deleted_at"`
	FirstSeenAt pgtype.Timestamptz   `json:"first_seen_at"`
	EntityType  DatabaseEntityType   `json:"entity_type"`
	ParentID    *uuid.UUID           `json:"parent_id"`
	Name        string               `json:"name"`
	Attributes  []byte               `json:"attributes"`
	CreatedAt   pgtype.Timestamptz   `json:"created_at"`
}

type MigrationStatement struct {
	ID           uuid.UUID                `json:"id"`
	RawStatement string                   `json:"raw_statement"`
	Action       MigrationStatementAction `json:"action"`
	Status       MigrationStatus          `json:"status"`
	Target       pgtype.Text              `json:"target"`
	RelationName pgtype.Text              `json:"relation_name"`
}

type Project struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectAccessToken struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Hash      string             `json:"hash"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectsSource struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Source    string             `json:"source"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Rule struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Type             RuleType           `json:"type"`
	DatabaseEntityID uuid.UUID          `json:"database_entity_id"`
	DatabaseID       uuid.UUID          `json:"database_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Table struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	SchemaID uuid.UUID `json:"schema_id"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}
