// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs
    (database_id, status, environment, completed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, database_id, status, environment, started_at, completed_at, created_at
`

type CreatePipelineRunParams struct {
	DatabaseID  uuid.UUID          `json:"database_id"`
	Status      MigrationStatus    `json:"status"`
	Environment pgtype.Text        `json:"environment"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, createPipelineRun,
		arg.DatabaseID,
		arg.Status,
		arg.Environment,
		arg.CompletedAt,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Status,
		&i.Environment,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPipelineRunByDatabaseIdAndId = `-- name: GetPipelineRunByDatabaseIdAndId :one
SELECT id, database_id, status, environment, started_at, completed_at, created_at
FROM pipeline_runs
WHERE database_id = $1
  AND id = $2
LIMIT 1
`

type GetPipelineRunByDatabaseIdAndIdParams struct {
	DatabaseID uuid.UUID `json:"database_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) GetPipelineRunByDatabaseIdAndId(ctx context.Context, arg GetPipelineRunByDatabaseIdAndIdParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRunByDatabaseIdAndId, arg.DatabaseID, arg.ID)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Status,
		&i.Environment,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPipelineRunsByDatabaseId = `-- name: GetPipelineRunsByDatabaseId :many
SELECT id, database_id, status, environment, started_at, completed_at, created_at
FROM pipeline_runs
WHERE database_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPipelineRunsByDatabaseId(ctx context.Context, databaseID uuid.UUID) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, getPipelineRunsByDatabaseId, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Status,
			&i.Environment,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
