// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_access_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectSecretKey = `-- name: CreateProjectSecretKey :one
INSERT INTO project_access_tokens (project_id, name, prefix, hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, expires_at, created_at, updated_at
`

type CreateProjectSecretKeyParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Hash      string             `json:"hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateProjectSecretKeyRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProjectSecretKey(ctx context.Context, arg CreateProjectSecretKeyParams) (CreateProjectSecretKeyRow, error) {
	row := q.db.QueryRow(ctx, createProjectSecretKey,
		arg.ProjectID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.ExpiresAt,
	)
	var i CreateProjectSecretKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectAccessToken = `-- name: DeleteProjectAccessToken :exec
DELETE FROM project_access_tokens WHERE project_id = $1 AND id = $2
`

type DeleteProjectAccessTokenParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SecretID  uuid.UUID `json:"secret_id"`
}

func (q *Queries) DeleteProjectAccessToken(ctx context.Context, arg DeleteProjectAccessTokenParams) error {
	_, err := q.db.Exec(ctx, deleteProjectAccessToken, arg.ProjectID, arg.SecretID)
	return err
}

const getProjectAccessTokens = `-- name: GetProjectAccessTokens :many
SELECT id, project_id, name, prefix, hash, last_used, expires_at, created_at, updated_at
FROM project_access_tokens
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectAccessTokens(ctx context.Context, projectID uuid.UUID) ([]ProjectAccessToken, error) {
	rows, err := q.db.Query(ctx, getProjectAccessTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectAccessToken{}
	for rows.Next() {
		var i ProjectAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.LastUsed,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectBySecretPrefix = `-- name: GetProjectBySecretPrefix :one
SELECT p.id, p.name, p.created_at, p.updated_at
FROM project_access_tokens pat
JOIN projects p ON p.id = pat.project_id
WHERE pat.prefix = $1
LIMIT 1
`

func (q *Queries) GetProjectBySecretPrefix(ctx context.Context, prefix string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySecretPrefix, prefix)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSecretKeyByID = `-- name: GetProjectSecretKeyByID :one
SELECT id, project_id, name, expires_at, created_at, updated_at
FROM project_access_tokens
WHERE id = $1
  AND project_id = $2
LIMIT 1
`

type GetProjectSecretKeyByIDParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type GetProjectSecretKeyByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectSecretKeyByID(ctx context.Context, arg GetProjectSecretKeyByIDParams) (GetProjectSecretKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectSecretKeyByID, arg.ID, arg.ProjectID)
	var i GetProjectSecretKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
