// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error)
	CreateDatabaseEntity(ctx context.Context, arg CreateDatabaseEntityParams) (DatabaseEntity, error)
	CreateProject(ctx context.Context, name string) (Project, error)
	CreateProjectSecretKey(ctx context.Context, arg CreateProjectSecretKeyParams) (CreateProjectSecretKeyRow, error)
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	DeleteDatabase(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteProjectAccessToken(ctx context.Context, arg DeleteProjectAccessTokenParams) error
	DeleteRule(ctx context.Context, arg DeleteRuleParams) error
	GetDatabase(ctx context.Context, id uuid.UUID) (Database, error)
	GetDatabaseByIDAndProjectID(ctx context.Context, arg GetDatabaseByIDAndProjectIDParams) (Database, error)
	GetDatabaseByIdAndProject(ctx context.Context, arg GetDatabaseByIdAndProjectParams) (Database, error)
	GetDatabaseByNameAndProject(ctx context.Context, arg GetDatabaseByNameAndProjectParams) (Database, error)
	GetDatabaseEntitiesByDatabaseId(ctx context.Context, arg GetDatabaseEntitiesByDatabaseIdParams) ([]DatabaseEntity, error)
	GetDatabaseEntitiesByDatabaseIdAndParentId(ctx context.Context, arg GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]DatabaseEntity, error)
	GetDatabaseEntitiesByProjectId(ctx context.Context, projectID uuid.UUID) ([]DatabaseEntity, error)
	GetDatabaseEntity(ctx context.Context, id uuid.UUID) (DatabaseEntity, error)
	GetDatabaseEntityByDatabaseIdAndTypeAndName(ctx context.Context, arg GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) (DatabaseEntity, error)
	GetDatabaseEntityByProjectIdAndId(ctx context.Context, arg GetDatabaseEntityByProjectIdAndIdParams) (DatabaseEntity, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectAccessTokens(ctx context.Context, projectID uuid.UUID) ([]ProjectAccessToken, error)
	GetProjectBySecretPrefix(ctx context.Context, prefix string) (Project, error)
	GetProjectSecretKeyByID(ctx context.Context, arg GetProjectSecretKeyByIDParams) (GetProjectSecretKeyByIDRow, error)
	GetProjects(ctx context.Context) ([]Project, error)
	GetRule(ctx context.Context, arg GetRuleParams) (Rule, error)
	GetRuleWithEntity(ctx context.Context, arg GetRuleWithEntityParams) (GetRuleWithEntityRow, error)
	GetRulesWithEntities(ctx context.Context, databaseID uuid.UUID) ([]GetRulesWithEntitiesRow, error)
	ListDatabasesByProject(ctx context.Context, projectID uuid.UUID) ([]Database, error)
	ListRulesByCriteria(ctx context.Context, arg ListRulesByCriteriaParams) ([]Rule, error)
	ListRulesByDatabaseId(ctx context.Context, databaseID uuid.UUID) ([]Rule, error)
	UpdateDatabase(ctx context.Context, arg UpdateDatabaseParams) (Database, error)
	UpdateDatabaseSyncFail(ctx context.Context, arg UpdateDatabaseSyncFailParams) (Database, error)
	UpdateDatabaseSyncedAt(ctx context.Context, arg UpdateDatabaseSyncedAtParams) (Database, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRule(ctx context.Context, arg UpdateRuleParams) error
}

var _ Querier = (*Queries)(nil)
