// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/walmaa/skemr-api/db/sqlc"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateDatabase provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateDatabase(ctx context.Context, arg sqlc.CreateDatabaseParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabase")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDatabaseParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDatabaseParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateDatabaseParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatabase'
type MockQuerier_CreateDatabase_Call struct {
	*mock.Call
}

// CreateDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateDatabaseParams
func (_e *MockQuerier_Expecter) CreateDatabase(ctx interface{}, arg interface{}) *MockQuerier_CreateDatabase_Call {
	return &MockQuerier_CreateDatabase_Call{Call: _e.mock.On("CreateDatabase", ctx, arg)}
}

func (_c *MockQuerier_CreateDatabase_Call) Run(run func(ctx context.Context, arg sqlc.CreateDatabaseParams)) *MockQuerier_CreateDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateDatabaseParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateDatabaseParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateDatabase_Call) Return(database sqlc.Database, err error) *MockQuerier_CreateDatabase_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_CreateDatabase_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateDatabaseParams) (sqlc.Database, error)) *MockQuerier_CreateDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDatabaseEntity provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateDatabaseEntity(ctx context.Context, arg sqlc.CreateDatabaseEntityParams) (sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDatabaseEntity")
	}

	var r0 sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDatabaseEntityParams) (sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDatabaseEntityParams) sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.DatabaseEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateDatabaseEntityParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateDatabaseEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDatabaseEntity'
type MockQuerier_CreateDatabaseEntity_Call struct {
	*mock.Call
}

// CreateDatabaseEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateDatabaseEntityParams
func (_e *MockQuerier_Expecter) CreateDatabaseEntity(ctx interface{}, arg interface{}) *MockQuerier_CreateDatabaseEntity_Call {
	return &MockQuerier_CreateDatabaseEntity_Call{Call: _e.mock.On("CreateDatabaseEntity", ctx, arg)}
}

func (_c *MockQuerier_CreateDatabaseEntity_Call) Run(run func(ctx context.Context, arg sqlc.CreateDatabaseEntityParams)) *MockQuerier_CreateDatabaseEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateDatabaseEntityParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateDatabaseEntityParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateDatabaseEntity_Call) Return(databaseEntity sqlc.DatabaseEntity, err error) *MockQuerier_CreateDatabaseEntity_Call {
	_c.Call.Return(databaseEntity, err)
	return _c
}

func (_c *MockQuerier_CreateDatabaseEntity_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateDatabaseEntityParams) (sqlc.DatabaseEntity, error)) *MockQuerier_CreateDatabaseEntity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateProject(ctx context.Context, name string) (sqlc.Project, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 sqlc.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Project, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Project); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(sqlc.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockQuerier_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuerier_Expecter) CreateProject(ctx interface{}, name interface{}) *MockQuerier_CreateProject_Call {
	return &MockQuerier_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, name)}
}

func (_c *MockQuerier_CreateProject_Call) Run(run func(ctx context.Context, name string)) *MockQuerier_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateProject_Call) Return(project sqlc.Project, err error) *MockQuerier_CreateProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockQuerier_CreateProject_Call) RunAndReturn(run func(ctx context.Context, name string) (sqlc.Project, error)) *MockQuerier_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProjectSecretKey provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateProjectSecretKey(ctx context.Context, arg sqlc.CreateProjectSecretKeyParams) (sqlc.CreateProjectSecretKeyRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectSecretKey")
	}

	var r0 sqlc.CreateProjectSecretKeyRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateProjectSecretKeyParams) (sqlc.CreateProjectSecretKeyRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateProjectSecretKeyParams) sqlc.CreateProjectSecretKeyRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.CreateProjectSecretKeyRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateProjectSecretKeyParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateProjectSecretKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectSecretKey'
type MockQuerier_CreateProjectSecretKey_Call struct {
	*mock.Call
}

// CreateProjectSecretKey is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateProjectSecretKeyParams
func (_e *MockQuerier_Expecter) CreateProjectSecretKey(ctx interface{}, arg interface{}) *MockQuerier_CreateProjectSecretKey_Call {
	return &MockQuerier_CreateProjectSecretKey_Call{Call: _e.mock.On("CreateProjectSecretKey", ctx, arg)}
}

func (_c *MockQuerier_CreateProjectSecretKey_Call) Run(run func(ctx context.Context, arg sqlc.CreateProjectSecretKeyParams)) *MockQuerier_CreateProjectSecretKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateProjectSecretKeyParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateProjectSecretKeyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateProjectSecretKey_Call) Return(createProjectSecretKeyRow sqlc.CreateProjectSecretKeyRow, err error) *MockQuerier_CreateProjectSecretKey_Call {
	_c.Call.Return(createProjectSecretKeyRow, err)
	return _c
}

func (_c *MockQuerier_CreateProjectSecretKey_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateProjectSecretKeyParams) (sqlc.CreateProjectSecretKeyRow, error)) *MockQuerier_CreateProjectSecretKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRule provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateRule(ctx context.Context, arg sqlc.CreateRuleParams) (sqlc.Rule, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRuleParams) (sqlc.Rule, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRuleParams) sqlc.Rule); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateRuleParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockQuerier_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateRuleParams
func (_e *MockQuerier_Expecter) CreateRule(ctx interface{}, arg interface{}) *MockQuerier_CreateRule_Call {
	return &MockQuerier_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, arg)}
}

func (_c *MockQuerier_CreateRule_Call) Run(run func(ctx context.Context, arg sqlc.CreateRuleParams)) *MockQuerier_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateRule_Call) Return(rule sqlc.Rule, err error) *MockQuerier_CreateRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockQuerier_CreateRule_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateRuleParams) (sqlc.Rule, error)) *MockQuerier_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDatabase provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteDatabase(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDatabase'
type MockQuerier_DeleteDatabase_Call struct {
	*mock.Call
}

// DeleteDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeleteDatabase(ctx interface{}, id interface{}) *MockQuerier_DeleteDatabase_Call {
	return &MockQuerier_DeleteDatabase_Call{Call: _e.mock.On("DeleteDatabase", ctx, id)}
}

func (_c *MockQuerier_DeleteDatabase_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeleteDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteDatabase_Call) Return(err error) *MockQuerier_DeleteDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteDatabase_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockQuerier_DeleteDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteProject(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockQuerier_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockQuerier_DeleteProject_Call {
	return &MockQuerier_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockQuerier_DeleteProject_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteProject_Call) Return(err error) *MockQuerier_DeleteProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteProject_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockQuerier_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectAccessToken provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteProjectAccessToken(ctx context.Context, arg sqlc.DeleteProjectAccessTokenParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteProjectAccessTokenParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteProjectAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectAccessToken'
type MockQuerier_DeleteProjectAccessToken_Call struct {
	*mock.Call
}

// DeleteProjectAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteProjectAccessTokenParams
func (_e *MockQuerier_Expecter) DeleteProjectAccessToken(ctx interface{}, arg interface{}) *MockQuerier_DeleteProjectAccessToken_Call {
	return &MockQuerier_DeleteProjectAccessToken_Call{Call: _e.mock.On("DeleteProjectAccessToken", ctx, arg)}
}

func (_c *MockQuerier_DeleteProjectAccessToken_Call) Run(run func(ctx context.Context, arg sqlc.DeleteProjectAccessTokenParams)) *MockQuerier_DeleteProjectAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteProjectAccessTokenParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteProjectAccessTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteProjectAccessToken_Call) Return(err error) *MockQuerier_DeleteProjectAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteProjectAccessToken_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteProjectAccessTokenParams) error) *MockQuerier_DeleteProjectAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteRule(ctx context.Context, arg sqlc.DeleteRuleParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteRuleParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockQuerier_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteRuleParams
func (_e *MockQuerier_Expecter) DeleteRule(ctx interface{}, arg interface{}) *MockQuerier_DeleteRule_Call {
	return &MockQuerier_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, arg)}
}

func (_c *MockQuerier_DeleteRule_Call) Run(run func(ctx context.Context, arg sqlc.DeleteRuleParams)) *MockQuerier_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteRule_Call) Return(err error) *MockQuerier_DeleteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteRule_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteRuleParams) error) *MockQuerier_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabase provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabase(ctx context.Context, id uuid.UUID) (sqlc.Database, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabase")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Database, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Database); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabase'
type MockQuerier_GetDatabase_Call struct {
	*mock.Call
}

// GetDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetDatabase(ctx interface{}, id interface{}) *MockQuerier_GetDatabase_Call {
	return &MockQuerier_GetDatabase_Call{Call: _e.mock.On("GetDatabase", ctx, id)}
}

func (_c *MockQuerier_GetDatabase_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabase_Call) Return(database sqlc.Database, err error) *MockQuerier_GetDatabase_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_GetDatabase_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Database, error)) *MockQuerier_GetDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseByIDAndProjectID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseByIDAndProjectID(ctx context.Context, arg sqlc.GetDatabaseByIDAndProjectIDParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseByIDAndProjectID")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByIDAndProjectIDParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByIDAndProjectIDParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseByIDAndProjectIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseByIDAndProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseByIDAndProjectID'
type MockQuerier_GetDatabaseByIDAndProjectID_Call struct {
	*mock.Call
}

// GetDatabaseByIDAndProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseByIDAndProjectIDParams
func (_e *MockQuerier_Expecter) GetDatabaseByIDAndProjectID(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseByIDAndProjectID_Call {
	return &MockQuerier_GetDatabaseByIDAndProjectID_Call{Call: _e.mock.On("GetDatabaseByIDAndProjectID", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseByIDAndProjectID_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseByIDAndProjectIDParams)) *MockQuerier_GetDatabaseByIDAndProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseByIDAndProjectIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseByIDAndProjectIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseByIDAndProjectID_Call) Return(database sqlc.Database, err error) *MockQuerier_GetDatabaseByIDAndProjectID_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseByIDAndProjectID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseByIDAndProjectIDParams) (sqlc.Database, error)) *MockQuerier_GetDatabaseByIDAndProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseByIdAndProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseByIdAndProject(ctx context.Context, arg sqlc.GetDatabaseByIdAndProjectParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseByIdAndProject")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByIdAndProjectParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByIdAndProjectParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseByIdAndProjectParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseByIdAndProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseByIdAndProject'
type MockQuerier_GetDatabaseByIdAndProject_Call struct {
	*mock.Call
}

// GetDatabaseByIdAndProject is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseByIdAndProjectParams
func (_e *MockQuerier_Expecter) GetDatabaseByIdAndProject(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseByIdAndProject_Call {
	return &MockQuerier_GetDatabaseByIdAndProject_Call{Call: _e.mock.On("GetDatabaseByIdAndProject", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseByIdAndProject_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseByIdAndProjectParams)) *MockQuerier_GetDatabaseByIdAndProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseByIdAndProjectParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseByIdAndProjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseByIdAndProject_Call) Return(database sqlc.Database, err error) *MockQuerier_GetDatabaseByIdAndProject_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseByIdAndProject_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseByIdAndProjectParams) (sqlc.Database, error)) *MockQuerier_GetDatabaseByIdAndProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseByNameAndProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseByNameAndProject(ctx context.Context, arg sqlc.GetDatabaseByNameAndProjectParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseByNameAndProject")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByNameAndProjectParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseByNameAndProjectParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseByNameAndProjectParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseByNameAndProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseByNameAndProject'
type MockQuerier_GetDatabaseByNameAndProject_Call struct {
	*mock.Call
}

// GetDatabaseByNameAndProject is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseByNameAndProjectParams
func (_e *MockQuerier_Expecter) GetDatabaseByNameAndProject(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseByNameAndProject_Call {
	return &MockQuerier_GetDatabaseByNameAndProject_Call{Call: _e.mock.On("GetDatabaseByNameAndProject", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseByNameAndProject_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseByNameAndProjectParams)) *MockQuerier_GetDatabaseByNameAndProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseByNameAndProjectParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseByNameAndProjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseByNameAndProject_Call) Return(database sqlc.Database, err error) *MockQuerier_GetDatabaseByNameAndProject_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseByNameAndProject_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseByNameAndProjectParams) (sqlc.Database, error)) *MockQuerier_GetDatabaseByNameAndProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntities provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntities(ctx context.Context, arg sqlc.GetDatabaseEntitiesParams) ([]sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntities")
	}

	var r0 []sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntitiesParams) ([]sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntitiesParams) []sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.DatabaseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseEntitiesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntities'
type MockQuerier_GetDatabaseEntities_Call struct {
	*mock.Call
}

// GetDatabaseEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseEntitiesParams
func (_e *MockQuerier_Expecter) GetDatabaseEntities(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseEntities_Call {
	return &MockQuerier_GetDatabaseEntities_Call{Call: _e.mock.On("GetDatabaseEntities", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseEntities_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseEntitiesParams)) *MockQuerier_GetDatabaseEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseEntitiesParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseEntitiesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntities_Call) Return(databaseEntitys []sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntities_Call {
	_c.Call.Return(databaseEntitys, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntities_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseEntitiesParams) ([]sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntities_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntitiesByDatabaseId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntitiesByDatabaseId(ctx context.Context, databaseID uuid.UUID) ([]sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, databaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntitiesByDatabaseId")
	}

	var r0 []sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, databaseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, databaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.DatabaseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, databaseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntitiesByDatabaseId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntitiesByDatabaseId'
type MockQuerier_GetDatabaseEntitiesByDatabaseId_Call struct {
	*mock.Call
}

// GetDatabaseEntitiesByDatabaseId is a helper method to define mock.On call
//   - ctx context.Context
//   - databaseID uuid.UUID
func (_e *MockQuerier_Expecter) GetDatabaseEntitiesByDatabaseId(ctx interface{}, databaseID interface{}) *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call {
	return &MockQuerier_GetDatabaseEntitiesByDatabaseId_Call{Call: _e.mock.On("GetDatabaseEntitiesByDatabaseId", ctx, databaseID)}
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call) Run(run func(ctx context.Context, databaseID uuid.UUID)) *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call) Return(databaseEntitys []sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call {
	_c.Call.Return(databaseEntitys, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call) RunAndReturn(run func(ctx context.Context, databaseID uuid.UUID) ([]sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntitiesByDatabaseId_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntitiesByDatabaseIdAndParentId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntitiesByDatabaseIdAndParentId(ctx context.Context, arg sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntitiesByDatabaseIdAndParentId")
	}

	var r0 []sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams) []sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.DatabaseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntitiesByDatabaseIdAndParentId'
type MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call struct {
	*mock.Call
}

// GetDatabaseEntitiesByDatabaseIdAndParentId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams
func (_e *MockQuerier_Expecter) GetDatabaseEntitiesByDatabaseIdAndParentId(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call {
	return &MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call{Call: _e.mock.On("GetDatabaseEntitiesByDatabaseIdAndParentId", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams)) *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call) Return(databaseEntitys []sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call {
	_c.Call.Return(databaseEntitys, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseEntitiesByDatabaseIdAndParentIdParams) ([]sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntitiesByDatabaseIdAndParentId_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntitiesByProjectId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntitiesByProjectId(ctx context.Context, projectID uuid.UUID) ([]sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntitiesByProjectId")
	}

	var r0 []sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.DatabaseEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntitiesByProjectId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntitiesByProjectId'
type MockQuerier_GetDatabaseEntitiesByProjectId_Call struct {
	*mock.Call
}

// GetDatabaseEntitiesByProjectId is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockQuerier_Expecter) GetDatabaseEntitiesByProjectId(ctx interface{}, projectID interface{}) *MockQuerier_GetDatabaseEntitiesByProjectId_Call {
	return &MockQuerier_GetDatabaseEntitiesByProjectId_Call{Call: _e.mock.On("GetDatabaseEntitiesByProjectId", ctx, projectID)}
}

func (_c *MockQuerier_GetDatabaseEntitiesByProjectId_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockQuerier_GetDatabaseEntitiesByProjectId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByProjectId_Call) Return(databaseEntitys []sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntitiesByProjectId_Call {
	_c.Call.Return(databaseEntitys, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntitiesByProjectId_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntitiesByProjectId_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntity provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntity(ctx context.Context, id uuid.UUID) (sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntity")
	}

	var r0 sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.DatabaseEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntity'
type MockQuerier_GetDatabaseEntity_Call struct {
	*mock.Call
}

// GetDatabaseEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetDatabaseEntity(ctx interface{}, id interface{}) *MockQuerier_GetDatabaseEntity_Call {
	return &MockQuerier_GetDatabaseEntity_Call{Call: _e.mock.On("GetDatabaseEntity", ctx, id)}
}

func (_c *MockQuerier_GetDatabaseEntity_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetDatabaseEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntity_Call) Return(databaseEntity sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntity_Call {
	_c.Call.Return(databaseEntity, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntity_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntityByDatabaseIdAndTypeAndName provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntityByDatabaseIdAndTypeAndName(ctx context.Context, arg sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) (sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntityByDatabaseIdAndTypeAndName")
	}

	var r0 sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) (sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.DatabaseEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntityByDatabaseIdAndTypeAndName'
type MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call struct {
	*mock.Call
}

// GetDatabaseEntityByDatabaseIdAndTypeAndName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams
func (_e *MockQuerier_Expecter) GetDatabaseEntityByDatabaseIdAndTypeAndName(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call {
	return &MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call{Call: _e.mock.On("GetDatabaseEntityByDatabaseIdAndTypeAndName", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams)) *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call) Return(databaseEntity sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call {
	_c.Call.Return(databaseEntity, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseEntityByDatabaseIdAndTypeAndNameParams) (sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntityByDatabaseIdAndTypeAndName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseEntityByProjectIdAndId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseEntityByProjectIdAndId(ctx context.Context, arg sqlc.GetDatabaseEntityByProjectIdAndIdParams) (sqlc.DatabaseEntity, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseEntityByProjectIdAndId")
	}

	var r0 sqlc.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntityByProjectIdAndIdParams) (sqlc.DatabaseEntity, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDatabaseEntityByProjectIdAndIdParams) sqlc.DatabaseEntity); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.DatabaseEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDatabaseEntityByProjectIdAndIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseEntityByProjectIdAndId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseEntityByProjectIdAndId'
type MockQuerier_GetDatabaseEntityByProjectIdAndId_Call struct {
	*mock.Call
}

// GetDatabaseEntityByProjectIdAndId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDatabaseEntityByProjectIdAndIdParams
func (_e *MockQuerier_Expecter) GetDatabaseEntityByProjectIdAndId(ctx interface{}, arg interface{}) *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call {
	return &MockQuerier_GetDatabaseEntityByProjectIdAndId_Call{Call: _e.mock.On("GetDatabaseEntityByProjectIdAndId", ctx, arg)}
}

func (_c *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call) Run(run func(ctx context.Context, arg sqlc.GetDatabaseEntityByProjectIdAndIdParams)) *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDatabaseEntityByProjectIdAndIdParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDatabaseEntityByProjectIdAndIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call) Return(databaseEntity sqlc.DatabaseEntity, err error) *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call {
	_c.Call.Return(databaseEntity, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDatabaseEntityByProjectIdAndIdParams) (sqlc.DatabaseEntity, error)) *MockQuerier_GetDatabaseEntityByProjectIdAndId_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetProject(ctx context.Context, id uuid.UUID) (sqlc.Project, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 sqlc.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Project, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Project); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockQuerier_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetProject(ctx interface{}, id interface{}) *MockQuerier_GetProject_Call {
	return &MockQuerier_GetProject_Call{Call: _e.mock.On("GetProject", ctx, id)}
}

func (_c *MockQuerier_GetProject_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetProject_Call) Return(project sqlc.Project, err error) *MockQuerier_GetProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockQuerier_GetProject_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Project, error)) *MockQuerier_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectAccessTokens provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetProjectAccessTokens(ctx context.Context, projectID uuid.UUID) ([]sqlc.ProjectAccessToken, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectAccessTokens")
	}

	var r0 []sqlc.ProjectAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.ProjectAccessToken, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.ProjectAccessToken); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ProjectAccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetProjectAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectAccessTokens'
type MockQuerier_GetProjectAccessTokens_Call struct {
	*mock.Call
}

// GetProjectAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockQuerier_Expecter) GetProjectAccessTokens(ctx interface{}, projectID interface{}) *MockQuerier_GetProjectAccessTokens_Call {
	return &MockQuerier_GetProjectAccessTokens_Call{Call: _e.mock.On("GetProjectAccessTokens", ctx, projectID)}
}

func (_c *MockQuerier_GetProjectAccessTokens_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockQuerier_GetProjectAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetProjectAccessTokens_Call) Return(projectAccessTokens []sqlc.ProjectAccessToken, err error) *MockQuerier_GetProjectAccessTokens_Call {
	_c.Call.Return(projectAccessTokens, err)
	return _c
}

func (_c *MockQuerier_GetProjectAccessTokens_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]sqlc.ProjectAccessToken, error)) *MockQuerier_GetProjectAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectBySecretPrefix provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetProjectBySecretPrefix(ctx context.Context, prefix string) (sqlc.Project, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectBySecretPrefix")
	}

	var r0 sqlc.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Project, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Project); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Get(0).(sqlc.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetProjectBySecretPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectBySecretPrefix'
type MockQuerier_GetProjectBySecretPrefix_Call struct {
	*mock.Call
}

// GetProjectBySecretPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockQuerier_Expecter) GetProjectBySecretPrefix(ctx interface{}, prefix interface{}) *MockQuerier_GetProjectBySecretPrefix_Call {
	return &MockQuerier_GetProjectBySecretPrefix_Call{Call: _e.mock.On("GetProjectBySecretPrefix", ctx, prefix)}
}

func (_c *MockQuerier_GetProjectBySecretPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockQuerier_GetProjectBySecretPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetProjectBySecretPrefix_Call) Return(project sqlc.Project, err error) *MockQuerier_GetProjectBySecretPrefix_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockQuerier_GetProjectBySecretPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) (sqlc.Project, error)) *MockQuerier_GetProjectBySecretPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectSecretKeyByID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetProjectSecretKeyByID(ctx context.Context, arg sqlc.GetProjectSecretKeyByIDParams) (sqlc.GetProjectSecretKeyByIDRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectSecretKeyByID")
	}

	var r0 sqlc.GetProjectSecretKeyByIDRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectSecretKeyByIDParams) (sqlc.GetProjectSecretKeyByIDRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectSecretKeyByIDParams) sqlc.GetProjectSecretKeyByIDRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.GetProjectSecretKeyByIDRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetProjectSecretKeyByIDParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetProjectSecretKeyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectSecretKeyByID'
type MockQuerier_GetProjectSecretKeyByID_Call struct {
	*mock.Call
}

// GetProjectSecretKeyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetProjectSecretKeyByIDParams
func (_e *MockQuerier_Expecter) GetProjectSecretKeyByID(ctx interface{}, arg interface{}) *MockQuerier_GetProjectSecretKeyByID_Call {
	return &MockQuerier_GetProjectSecretKeyByID_Call{Call: _e.mock.On("GetProjectSecretKeyByID", ctx, arg)}
}

func (_c *MockQuerier_GetProjectSecretKeyByID_Call) Run(run func(ctx context.Context, arg sqlc.GetProjectSecretKeyByIDParams)) *MockQuerier_GetProjectSecretKeyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetProjectSecretKeyByIDParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetProjectSecretKeyByIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetProjectSecretKeyByID_Call) Return(getProjectSecretKeyByIDRow sqlc.GetProjectSecretKeyByIDRow, err error) *MockQuerier_GetProjectSecretKeyByID_Call {
	_c.Call.Return(getProjectSecretKeyByIDRow, err)
	return _c
}

func (_c *MockQuerier_GetProjectSecretKeyByID_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetProjectSecretKeyByIDParams) (sqlc.GetProjectSecretKeyByIDRow, error)) *MockQuerier_GetProjectSecretKeyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetProjects(ctx context.Context) ([]sqlc.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProjects")
	}

	var r0 []sqlc.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]sqlc.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []sqlc.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockQuerier_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) GetProjects(ctx interface{}) *MockQuerier_GetProjects_Call {
	return &MockQuerier_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx)}
}

func (_c *MockQuerier_GetProjects_Call) Run(run func(ctx context.Context)) *MockQuerier_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_GetProjects_Call) Return(projects []sqlc.Project, err error) *MockQuerier_GetProjects_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockQuerier_GetProjects_Call) RunAndReturn(run func(ctx context.Context) ([]sqlc.Project, error)) *MockQuerier_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRule(ctx context.Context, arg sqlc.GetRuleParams) (sqlc.Rule, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleParams) (sqlc.Rule, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleParams) sqlc.Rule); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetRuleParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockQuerier_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetRuleParams
func (_e *MockQuerier_Expecter) GetRule(ctx interface{}, arg interface{}) *MockQuerier_GetRule_Call {
	return &MockQuerier_GetRule_Call{Call: _e.mock.On("GetRule", ctx, arg)}
}

func (_c *MockQuerier_GetRule_Call) Run(run func(ctx context.Context, arg sqlc.GetRuleParams)) *MockQuerier_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRule_Call) Return(rule sqlc.Rule, err error) *MockQuerier_GetRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockQuerier_GetRule_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetRuleParams) (sqlc.Rule, error)) *MockQuerier_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuleWithEntity provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRuleWithEntity(ctx context.Context, arg sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleWithEntity")
	}

	var r0 sqlc.GetRuleWithEntityRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleWithEntityParams) sqlc.GetRuleWithEntityRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.GetRuleWithEntityRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetRuleWithEntityParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRuleWithEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuleWithEntity'
type MockQuerier_GetRuleWithEntity_Call struct {
	*mock.Call
}

// GetRuleWithEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetRuleWithEntityParams
func (_e *MockQuerier_Expecter) GetRuleWithEntity(ctx interface{}, arg interface{}) *MockQuerier_GetRuleWithEntity_Call {
	return &MockQuerier_GetRuleWithEntity_Call{Call: _e.mock.On("GetRuleWithEntity", ctx, arg)}
}

func (_c *MockQuerier_GetRuleWithEntity_Call) Run(run func(ctx context.Context, arg sqlc.GetRuleWithEntityParams)) *MockQuerier_GetRuleWithEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetRuleWithEntityParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetRuleWithEntityParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRuleWithEntity_Call) Return(getRuleWithEntityRow sqlc.GetRuleWithEntityRow, err error) *MockQuerier_GetRuleWithEntity_Call {
	_c.Call.Return(getRuleWithEntityRow, err)
	return _c
}

func (_c *MockQuerier_GetRuleWithEntity_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error)) *MockQuerier_GetRuleWithEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetRulesWithEntities provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRulesWithEntities(ctx context.Context, databaseID uuid.UUID) ([]sqlc.GetRulesWithEntitiesRow, error) {
	ret := _mock.Called(ctx, databaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetRulesWithEntities")
	}

	var r0 []sqlc.GetRulesWithEntitiesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.GetRulesWithEntitiesRow, error)); ok {
		return returnFunc(ctx, databaseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.GetRulesWithEntitiesRow); ok {
		r0 = returnFunc(ctx, databaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRulesWithEntitiesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, databaseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRulesWithEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRulesWithEntities'
type MockQuerier_GetRulesWithEntities_Call struct {
	*mock.Call
}

// GetRulesWithEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - databaseID uuid.UUID
func (_e *MockQuerier_Expecter) GetRulesWithEntities(ctx interface{}, databaseID interface{}) *MockQuerier_GetRulesWithEntities_Call {
	return &MockQuerier_GetRulesWithEntities_Call{Call: _e.mock.On("GetRulesWithEntities", ctx, databaseID)}
}

func (_c *MockQuerier_GetRulesWithEntities_Call) Run(run func(ctx context.Context, databaseID uuid.UUID)) *MockQuerier_GetRulesWithEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRulesWithEntities_Call) Return(getRulesWithEntitiesRows []sqlc.GetRulesWithEntitiesRow, err error) *MockQuerier_GetRulesWithEntities_Call {
	_c.Call.Return(getRulesWithEntitiesRows, err)
	return _c
}

func (_c *MockQuerier_GetRulesWithEntities_Call) RunAndReturn(run func(ctx context.Context, databaseID uuid.UUID) ([]sqlc.GetRulesWithEntitiesRow, error)) *MockQuerier_GetRulesWithEntities_Call {
	_c.Call.Return(run)
	return _c
}

// ListDatabasesByProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListDatabasesByProject(ctx context.Context, projectID uuid.UUID) ([]sqlc.Database, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListDatabasesByProject")
	}

	var r0 []sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.Database, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.Database); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Database)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListDatabasesByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDatabasesByProject'
type MockQuerier_ListDatabasesByProject_Call struct {
	*mock.Call
}

// ListDatabasesByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockQuerier_Expecter) ListDatabasesByProject(ctx interface{}, projectID interface{}) *MockQuerier_ListDatabasesByProject_Call {
	return &MockQuerier_ListDatabasesByProject_Call{Call: _e.mock.On("ListDatabasesByProject", ctx, projectID)}
}

func (_c *MockQuerier_ListDatabasesByProject_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockQuerier_ListDatabasesByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListDatabasesByProject_Call) Return(databases []sqlc.Database, err error) *MockQuerier_ListDatabasesByProject_Call {
	_c.Call.Return(databases, err)
	return _c
}

func (_c *MockQuerier_ListDatabasesByProject_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]sqlc.Database, error)) *MockQuerier_ListDatabasesByProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListRulesByCriteria provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListRulesByCriteria(ctx context.Context, arg sqlc.ListRulesByCriteriaParams) ([]sqlc.Rule, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRulesByCriteria")
	}

	var r0 []sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListRulesByCriteriaParams) ([]sqlc.Rule, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.ListRulesByCriteriaParams) []sqlc.Rule); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.ListRulesByCriteriaParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListRulesByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRulesByCriteria'
type MockQuerier_ListRulesByCriteria_Call struct {
	*mock.Call
}

// ListRulesByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.ListRulesByCriteriaParams
func (_e *MockQuerier_Expecter) ListRulesByCriteria(ctx interface{}, arg interface{}) *MockQuerier_ListRulesByCriteria_Call {
	return &MockQuerier_ListRulesByCriteria_Call{Call: _e.mock.On("ListRulesByCriteria", ctx, arg)}
}

func (_c *MockQuerier_ListRulesByCriteria_Call) Run(run func(ctx context.Context, arg sqlc.ListRulesByCriteriaParams)) *MockQuerier_ListRulesByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.ListRulesByCriteriaParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.ListRulesByCriteriaParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListRulesByCriteria_Call) Return(rules []sqlc.Rule, err error) *MockQuerier_ListRulesByCriteria_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockQuerier_ListRulesByCriteria_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.ListRulesByCriteriaParams) ([]sqlc.Rule, error)) *MockQuerier_ListRulesByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// ListRulesByDatabaseId provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListRulesByDatabaseId(ctx context.Context, databaseID uuid.UUID) ([]sqlc.Rule, error) {
	ret := _mock.Called(ctx, databaseID)

	if len(ret) == 0 {
		panic("no return value specified for ListRulesByDatabaseId")
	}

	var r0 []sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]sqlc.Rule, error)); ok {
		return returnFunc(ctx, databaseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []sqlc.Rule); ok {
		r0 = returnFunc(ctx, databaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, databaseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListRulesByDatabaseId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRulesByDatabaseId'
type MockQuerier_ListRulesByDatabaseId_Call struct {
	*mock.Call
}

// ListRulesByDatabaseId is a helper method to define mock.On call
//   - ctx context.Context
//   - databaseID uuid.UUID
func (_e *MockQuerier_Expecter) ListRulesByDatabaseId(ctx interface{}, databaseID interface{}) *MockQuerier_ListRulesByDatabaseId_Call {
	return &MockQuerier_ListRulesByDatabaseId_Call{Call: _e.mock.On("ListRulesByDatabaseId", ctx, databaseID)}
}

func (_c *MockQuerier_ListRulesByDatabaseId_Call) Run(run func(ctx context.Context, databaseID uuid.UUID)) *MockQuerier_ListRulesByDatabaseId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListRulesByDatabaseId_Call) Return(rules []sqlc.Rule, err error) *MockQuerier_ListRulesByDatabaseId_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *MockQuerier_ListRulesByDatabaseId_Call) RunAndReturn(run func(ctx context.Context, databaseID uuid.UUID) ([]sqlc.Rule, error)) *MockQuerier_ListRulesByDatabaseId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatabase provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateDatabase(ctx context.Context, arg sqlc.UpdateDatabaseParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatabase")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateDatabaseParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatabase'
type MockQuerier_UpdateDatabase_Call struct {
	*mock.Call
}

// UpdateDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateDatabaseParams
func (_e *MockQuerier_Expecter) UpdateDatabase(ctx interface{}, arg interface{}) *MockQuerier_UpdateDatabase_Call {
	return &MockQuerier_UpdateDatabase_Call{Call: _e.mock.On("UpdateDatabase", ctx, arg)}
}

func (_c *MockQuerier_UpdateDatabase_Call) Run(run func(ctx context.Context, arg sqlc.UpdateDatabaseParams)) *MockQuerier_UpdateDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateDatabaseParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateDatabaseParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateDatabase_Call) Return(database sqlc.Database, err error) *MockQuerier_UpdateDatabase_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_UpdateDatabase_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateDatabaseParams) (sqlc.Database, error)) *MockQuerier_UpdateDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatabaseEntityAsDeleted provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateDatabaseEntityAsDeleted(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatabaseEntityAsDeleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateDatabaseEntityAsDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatabaseEntityAsDeleted'
type MockQuerier_UpdateDatabaseEntityAsDeleted_Call struct {
	*mock.Call
}

// UpdateDatabaseEntityAsDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) UpdateDatabaseEntityAsDeleted(ctx interface{}, id interface{}) *MockQuerier_UpdateDatabaseEntityAsDeleted_Call {
	return &MockQuerier_UpdateDatabaseEntityAsDeleted_Call{Call: _e.mock.On("UpdateDatabaseEntityAsDeleted", ctx, id)}
}

func (_c *MockQuerier_UpdateDatabaseEntityAsDeleted_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_UpdateDatabaseEntityAsDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateDatabaseEntityAsDeleted_Call) Return(err error) *MockQuerier_UpdateDatabaseEntityAsDeleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateDatabaseEntityAsDeleted_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockQuerier_UpdateDatabaseEntityAsDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatabaseSyncFail provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateDatabaseSyncFail(ctx context.Context, arg sqlc.UpdateDatabaseSyncFailParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatabaseSyncFail")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseSyncFailParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseSyncFailParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateDatabaseSyncFailParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateDatabaseSyncFail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatabaseSyncFail'
type MockQuerier_UpdateDatabaseSyncFail_Call struct {
	*mock.Call
}

// UpdateDatabaseSyncFail is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateDatabaseSyncFailParams
func (_e *MockQuerier_Expecter) UpdateDatabaseSyncFail(ctx interface{}, arg interface{}) *MockQuerier_UpdateDatabaseSyncFail_Call {
	return &MockQuerier_UpdateDatabaseSyncFail_Call{Call: _e.mock.On("UpdateDatabaseSyncFail", ctx, arg)}
}

func (_c *MockQuerier_UpdateDatabaseSyncFail_Call) Run(run func(ctx context.Context, arg sqlc.UpdateDatabaseSyncFailParams)) *MockQuerier_UpdateDatabaseSyncFail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateDatabaseSyncFailParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateDatabaseSyncFailParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateDatabaseSyncFail_Call) Return(database sqlc.Database, err error) *MockQuerier_UpdateDatabaseSyncFail_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_UpdateDatabaseSyncFail_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateDatabaseSyncFailParams) (sqlc.Database, error)) *MockQuerier_UpdateDatabaseSyncFail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatabaseSyncedAt provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateDatabaseSyncedAt(ctx context.Context, arg sqlc.UpdateDatabaseSyncedAtParams) (sqlc.Database, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatabaseSyncedAt")
	}

	var r0 sqlc.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseSyncedAtParams) (sqlc.Database, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDatabaseSyncedAtParams) sqlc.Database); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateDatabaseSyncedAtParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateDatabaseSyncedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatabaseSyncedAt'
type MockQuerier_UpdateDatabaseSyncedAt_Call struct {
	*mock.Call
}

// UpdateDatabaseSyncedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateDatabaseSyncedAtParams
func (_e *MockQuerier_Expecter) UpdateDatabaseSyncedAt(ctx interface{}, arg interface{}) *MockQuerier_UpdateDatabaseSyncedAt_Call {
	return &MockQuerier_UpdateDatabaseSyncedAt_Call{Call: _e.mock.On("UpdateDatabaseSyncedAt", ctx, arg)}
}

func (_c *MockQuerier_UpdateDatabaseSyncedAt_Call) Run(run func(ctx context.Context, arg sqlc.UpdateDatabaseSyncedAtParams)) *MockQuerier_UpdateDatabaseSyncedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateDatabaseSyncedAtParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateDatabaseSyncedAtParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateDatabaseSyncedAt_Call) Return(database sqlc.Database, err error) *MockQuerier_UpdateDatabaseSyncedAt_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockQuerier_UpdateDatabaseSyncedAt_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateDatabaseSyncedAtParams) (sqlc.Database, error)) *MockQuerier_UpdateDatabaseSyncedAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateProject(ctx context.Context, arg sqlc.UpdateProjectParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateProjectParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockQuerier_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateProjectParams
func (_e *MockQuerier_Expecter) UpdateProject(ctx interface{}, arg interface{}) *MockQuerier_UpdateProject_Call {
	return &MockQuerier_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, arg)}
}

func (_c *MockQuerier_UpdateProject_Call) Run(run func(ctx context.Context, arg sqlc.UpdateProjectParams)) *MockQuerier_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateProjectParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateProjectParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateProject_Call) Return(err error) *MockQuerier_UpdateProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateProject_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateProjectParams) error) *MockQuerier_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateRule(ctx context.Context, arg sqlc.UpdateRuleParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateRuleParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockQuerier_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateRuleParams
func (_e *MockQuerier_Expecter) UpdateRule(ctx interface{}, arg interface{}) *MockQuerier_UpdateRule_Call {
	return &MockQuerier_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, arg)}
}

func (_c *MockQuerier_UpdateRule_Call) Run(run func(ctx context.Context, arg sqlc.UpdateRuleParams)) *MockQuerier_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateRule_Call) Return(err error) *MockQuerier_UpdateRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateRule_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateRuleParams) error) *MockQuerier_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}
