// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/walmaa/skemr-api/db/sqlc"
)

// NewMockRuleStore creates a new instance of MockRuleStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleStore {
	mock := &MockRuleStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuleStore is an autogenerated mock type for the RuleStore type
type MockRuleStore struct {
	mock.Mock
}

type MockRuleStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleStore) EXPECT() *MockRuleStore_Expecter {
	return &MockRuleStore_Expecter{mock: &_m.Mock}
}

// CreateRule provides a mock function for the type MockRuleStore
func (_mock *MockRuleStore) CreateRule(ctx context.Context, dto sqlc.CreateRuleParams) (sqlc.Rule, error) {
	ret := _mock.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRuleParams) (sqlc.Rule, error)); ok {
		return returnFunc(ctx, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRuleParams) sqlc.Rule); ok {
		r0 = returnFunc(ctx, dto)
	} else {
		r0 = ret.Get(0).(sqlc.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateRuleParams) error); ok {
		r1 = returnFunc(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleStore_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockRuleStore_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - dto sqlc.CreateRuleParams
func (_e *MockRuleStore_Expecter) CreateRule(ctx interface{}, dto interface{}) *MockRuleStore_CreateRule_Call {
	return &MockRuleStore_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, dto)}
}

func (_c *MockRuleStore_CreateRule_Call) Run(run func(ctx context.Context, dto sqlc.CreateRuleParams)) *MockRuleStore_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleStore_CreateRule_Call) Return(rule sqlc.Rule, err error) *MockRuleStore_CreateRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockRuleStore_CreateRule_Call) RunAndReturn(run func(ctx context.Context, dto sqlc.CreateRuleParams) (sqlc.Rule, error)) *MockRuleStore_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function for the type MockRuleStore
func (_mock *MockRuleStore) DeleteRule(ctx context.Context, params sqlc.DeleteRuleParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteRuleParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuleStore_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockRuleStore_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.DeleteRuleParams
func (_e *MockRuleStore_Expecter) DeleteRule(ctx interface{}, params interface{}) *MockRuleStore_DeleteRule_Call {
	return &MockRuleStore_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, params)}
}

func (_c *MockRuleStore_DeleteRule_Call) Run(run func(ctx context.Context, params sqlc.DeleteRuleParams)) *MockRuleStore_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteRuleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteRuleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleStore_DeleteRule_Call) Return(err error) *MockRuleStore_DeleteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuleStore_DeleteRule_Call) RunAndReturn(run func(ctx context.Context, params sqlc.DeleteRuleParams) error) *MockRuleStore_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuleByDatabaseAndName provides a mock function for the type MockRuleStore
func (_mock *MockRuleStore) GetRuleByDatabaseAndName(ctx context.Context, params sqlc.GetRuleByDatabaseAndNameParams) (sqlc.Rule, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleByDatabaseAndName")
	}

	var r0 sqlc.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleByDatabaseAndNameParams) (sqlc.Rule, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleByDatabaseAndNameParams) sqlc.Rule); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(sqlc.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetRuleByDatabaseAndNameParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleStore_GetRuleByDatabaseAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuleByDatabaseAndName'
type MockRuleStore_GetRuleByDatabaseAndName_Call struct {
	*mock.Call
}

// GetRuleByDatabaseAndName is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetRuleByDatabaseAndNameParams
func (_e *MockRuleStore_Expecter) GetRuleByDatabaseAndName(ctx interface{}, params interface{}) *MockRuleStore_GetRuleByDatabaseAndName_Call {
	return &MockRuleStore_GetRuleByDatabaseAndName_Call{Call: _e.mock.On("GetRuleByDatabaseAndName", ctx, params)}
}

func (_c *MockRuleStore_GetRuleByDatabaseAndName_Call) Run(run func(ctx context.Context, params sqlc.GetRuleByDatabaseAndNameParams)) *MockRuleStore_GetRuleByDatabaseAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetRuleByDatabaseAndNameParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetRuleByDatabaseAndNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleStore_GetRuleByDatabaseAndName_Call) Return(rule sqlc.Rule, err error) *MockRuleStore_GetRuleByDatabaseAndName_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockRuleStore_GetRuleByDatabaseAndName_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetRuleByDatabaseAndNameParams) (sqlc.Rule, error)) *MockRuleStore_GetRuleByDatabaseAndName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuleWithEntity provides a mock function for the type MockRuleStore
func (_mock *MockRuleStore) GetRuleWithEntity(ctx context.Context, params sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleWithEntity")
	}

	var r0 sqlc.GetRuleWithEntityRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRuleWithEntityParams) sqlc.GetRuleWithEntityRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(sqlc.GetRuleWithEntityRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetRuleWithEntityParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleStore_GetRuleWithEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuleWithEntity'
type MockRuleStore_GetRuleWithEntity_Call struct {
	*mock.Call
}

// GetRuleWithEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetRuleWithEntityParams
func (_e *MockRuleStore_Expecter) GetRuleWithEntity(ctx interface{}, params interface{}) *MockRuleStore_GetRuleWithEntity_Call {
	return &MockRuleStore_GetRuleWithEntity_Call{Call: _e.mock.On("GetRuleWithEntity", ctx, params)}
}

func (_c *MockRuleStore_GetRuleWithEntity_Call) Run(run func(ctx context.Context, params sqlc.GetRuleWithEntityParams)) *MockRuleStore_GetRuleWithEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetRuleWithEntityParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetRuleWithEntityParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleStore_GetRuleWithEntity_Call) Return(getRuleWithEntityRow sqlc.GetRuleWithEntityRow, err error) *MockRuleStore_GetRuleWithEntity_Call {
	_c.Call.Return(getRuleWithEntityRow, err)
	return _c
}

func (_c *MockRuleStore_GetRuleWithEntity_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetRuleWithEntityParams) (sqlc.GetRuleWithEntityRow, error)) *MockRuleStore_GetRuleWithEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetRulesWithEntities provides a mock function for the type MockRuleStore
func (_mock *MockRuleStore) GetRulesWithEntities(ctx context.Context, row sqlc.GetRulesWithEntitiesParams) ([]sqlc.GetRulesWithEntitiesRow, error) {
	ret := _mock.Called(ctx, row)

	if len(ret) == 0 {
		panic("no return value specified for GetRulesWithEntities")
	}

	var r0 []sqlc.GetRulesWithEntitiesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRulesWithEntitiesParams) ([]sqlc.GetRulesWithEntitiesRow, error)); ok {
		return returnFunc(ctx, row)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetRulesWithEntitiesParams) []sqlc.GetRulesWithEntitiesRow); ok {
		r0 = returnFunc(ctx, row)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRulesWithEntitiesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetRulesWithEntitiesParams) error); ok {
		r1 = returnFunc(ctx, row)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleStore_GetRulesWithEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRulesWithEntities'
type MockRuleStore_GetRulesWithEntities_Call struct {
	*mock.Call
}

// GetRulesWithEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - row sqlc.GetRulesWithEntitiesParams
func (_e *MockRuleStore_Expecter) GetRulesWithEntities(ctx interface{}, row interface{}) *MockRuleStore_GetRulesWithEntities_Call {
	return &MockRuleStore_GetRulesWithEntities_Call{Call: _e.mock.On("GetRulesWithEntities", ctx, row)}
}

func (_c *MockRuleStore_GetRulesWithEntities_Call) Run(run func(ctx context.Context, row sqlc.GetRulesWithEntitiesParams)) *MockRuleStore_GetRulesWithEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetRulesWithEntitiesParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetRulesWithEntitiesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleStore_GetRulesWithEntities_Call) Return(getRulesWithEntitiesRows []sqlc.GetRulesWithEntitiesRow, err error) *MockRuleStore_GetRulesWithEntities_Call {
	_c.Call.Return(getRulesWithEntitiesRows, err)
	return _c
}

func (_c *MockRuleStore_GetRulesWithEntities_Call) RunAndReturn(run func(ctx context.Context, row sqlc.GetRulesWithEntitiesParams) ([]sqlc.GetRulesWithEntitiesRow, error)) *MockRuleStore_GetRulesWithEntities_Call {
	_c.Call.Return(run)
	return _c
}
