// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/walmaa/skemr-common/models"
)

// NewMockScopeResolver creates a new instance of MockScopeResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScopeResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScopeResolver {
	mock := &MockScopeResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScopeResolver is an autogenerated mock type for the ScopeResolver type
type MockScopeResolver struct {
	mock.Mock
}

type MockScopeResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScopeResolver) EXPECT() *MockScopeResolver_Expecter {
	return &MockScopeResolver_Expecter{mock: &_m.Mock}
}

// RequireDatabase provides a mock function for the type MockScopeResolver
func (_mock *MockScopeResolver) RequireDatabase(c context.Context, projectId uuid.UUID, databaseId uuid.UUID) (models.Database, error) {
	ret := _mock.Called(c, projectId, databaseId)

	if len(ret) == 0 {
		panic("no return value specified for RequireDatabase")
	}

	var r0 models.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Database, error)); ok {
		return returnFunc(c, projectId, databaseId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Database); ok {
		r0 = returnFunc(c, projectId, databaseId)
	} else {
		r0 = ret.Get(0).(models.Database)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(c, projectId, databaseId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScopeResolver_RequireDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireDatabase'
type MockScopeResolver_RequireDatabase_Call struct {
	*mock.Call
}

// RequireDatabase is a helper method to define mock.On call
//   - c context.Context
//   - projectId uuid.UUID
//   - databaseId uuid.UUID
func (_e *MockScopeResolver_Expecter) RequireDatabase(c interface{}, projectId interface{}, databaseId interface{}) *MockScopeResolver_RequireDatabase_Call {
	return &MockScopeResolver_RequireDatabase_Call{Call: _e.mock.On("RequireDatabase", c, projectId, databaseId)}
}

func (_c *MockScopeResolver_RequireDatabase_Call) Run(run func(c context.Context, projectId uuid.UUID, databaseId uuid.UUID)) *MockScopeResolver_RequireDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScopeResolver_RequireDatabase_Call) Return(database models.Database, err error) *MockScopeResolver_RequireDatabase_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockScopeResolver_RequireDatabase_Call) RunAndReturn(run func(c context.Context, projectId uuid.UUID, databaseId uuid.UUID) (models.Database, error)) *MockScopeResolver_RequireDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// RequireDatabaseEntity provides a mock function for the type MockScopeResolver
func (_mock *MockScopeResolver) RequireDatabaseEntity(c context.Context, projectId uuid.UUID, databaseId uuid.UUID, entityId uuid.UUID) (models.DatabaseEntity, error) {
	ret := _mock.Called(c, projectId, databaseId, entityId)

	if len(ret) == 0 {
		panic("no return value specified for RequireDatabaseEntity")
	}

	var r0 models.DatabaseEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (models.DatabaseEntity, error)); ok {
		return returnFunc(c, projectId, databaseId, entityId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) models.DatabaseEntity); ok {
		r0 = returnFunc(c, projectId, databaseId, entityId)
	} else {
		r0 = ret.Get(0).(models.DatabaseEntity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(c, projectId, databaseId, entityId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScopeResolver_RequireDatabaseEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireDatabaseEntity'
type MockScopeResolver_RequireDatabaseEntity_Call struct {
	*mock.Call
}

// RequireDatabaseEntity is a helper method to define mock.On call
//   - c context.Context
//   - projectId uuid.UUID
//   - databaseId uuid.UUID
//   - entityId uuid.UUID
func (_e *MockScopeResolver_Expecter) RequireDatabaseEntity(c interface{}, projectId interface{}, databaseId interface{}, entityId interface{}) *MockScopeResolver_RequireDatabaseEntity_Call {
	return &MockScopeResolver_RequireDatabaseEntity_Call{Call: _e.mock.On("RequireDatabaseEntity", c, projectId, databaseId, entityId)}
}

func (_c *MockScopeResolver_RequireDatabaseEntity_Call) Run(run func(c context.Context, projectId uuid.UUID, databaseId uuid.UUID, entityId uuid.UUID)) *MockScopeResolver_RequireDatabaseEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScopeResolver_RequireDatabaseEntity_Call) Return(databaseEntity models.DatabaseEntity, err error) *MockScopeResolver_RequireDatabaseEntity_Call {
	_c.Call.Return(databaseEntity, err)
	return _c
}

func (_c *MockScopeResolver_RequireDatabaseEntity_Call) RunAndReturn(run func(c context.Context, projectId uuid.UUID, databaseId uuid.UUID, entityId uuid.UUID) (models.DatabaseEntity, error)) *MockScopeResolver_RequireDatabaseEntity_Call {
	_c.Call.Return(run)
	return _c
}
