name: build-and-test.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'

      - name: Install mockery
        run: go install github.com/vektra/mockery/v3@v3.5.3

      - name: Generate sqlc
        run: sqlc generate

      - name: Create mocks
        run: mockery

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race -shuffle=on ./...
